### ISSUE TITLE
setup doesn't work correctly

### ISSUE THREAD

**Issue by yawor** [foprel/openpyxl-dictreader#1]
Your setup.py is not correctly configured for a single module project. You're using a `packages` keyword in `setup()` function, but your project doesn't contain any packages.
You should use `py_modules=["dictreader"]` instead.

Also please consider changing the module name from `dictreader` to something more specific, for example `openpyxl_dictreader`, or just `pyxl_dictreader`. A generic `dictreader` could conflict with something else (I don't have any examples of conflicting packages at the moment though).

**Comment by foprel** [comment]
Thanks for your feedback. Both issues are solved now:

- Changed the module name from `dictreader` to `openpyxl_dictreader`
- Removed `packages` kwarg from `setup()` and replaced it with `py_modules=["openpyxl_dictreader"]`
