### ISSUE TITLE
openpyxl-dictreader forces use of outdated openpyxl package

### ISSUE THREAD

**Issue by mdkemp** [foprel/openpyxl-dictreader#10]
In requirements.txt, openpyxl==3.0.3 is a dependency; that's a two-year-old version of openpyxl (current is 3.0.9).  Installing openpyxl_dictreader in an environment that also uses openpyxl causes roll-back of openpyxl to that old version.

It appears that openpyxl_dictreader also works with the current version of openpyxl, 3.0.9.

Could requirements.txt please be changed to allow openpyxl==3.0.*, or some other appropriately-large version range?

(It looks like some of the other dependencies in requirements.txt may not be needed, by the way)

**Comment by foprel** [comment]
Hello @mdkemp,

Thank you for reaching out. This package indeed only supported `openpyxl=3.0.3`. Pull request #11 has resolved this issue. I will publish a new version of this package to [PyPI](https://pypi.org/project/openpyxl-dictreader/) today so it can be easily updated using `pip install openpyxl-dictreader --upgrade`.
