### ISSUE TITLE
"worksheet" should be a required, positional argument to DictReader.__init__

### ISSUE THREAD

**Issue by RHolton** [foprel/openpyxl-dictreader#3]
Is there any use-case of DictReader where the default value of None for worksheet does not result in an exception? There always needs to be a worksheet specified. So remove the default value and make it the parameter immediately following filename:

`def __init__(self, filename,  worksheet, fieldnames=None, restval=None, restkey=None, *args, **kwargs):  `

btw: I'm finding your module very useful!

**Comment by foprel** [comment]
Thank you for bringing this up. There's indeed no use-case for DictReader without specifying the worksheet. I have updated the package accordingly:

`def __init__(self, filename, worksheet, fieldnames=None, restval=None, restkey=None, *args, **kwargs):`

I have released a new version via PyPI. You can install it with pip:

`pip install openpyxl-dictreader==0.1.3 `

Good luck!
