### ISSUE TITLE
Can't specify keyword arguments to load_workbook

### ISSUE THREAD

**Issue by RHolton** [foprel/openpyxl-dictreader#4]
The load_workbook method takes several optional keyword arguments:

- read_only: optimised for reading, content cannot be edited
- keep_vba: preserve vba content
- data_only: controls whether cells with formulae have either the formula (default) or the value stored the last time Excel read the sheet
- keep_links: whether links to external workbooks should be preserved. The default is True

In order to read the values from Excel cells with formulas, data_only needs to be True. Others may be necessary as well.

I suggest passing kwargs (expanded with the ** operator) to load_workbook:

`self.wb = load_workbook(filename, **kwargs)`

**Comment by foprel** [comment]
I haven't come across this use-case yet, but I can understand that it's often necessary to pass additional kwargs to the load_workbook method. I have added `**kwargs` as an argument, as you suggested:

`self.wb = load_workbook(filename, **kwargs)`

I have mentioned this functionality in the README and released a new version via PyPI. You can install it with pip:

`pip install openpyxl-dictreader==0.1.3`

Good luck!
