### ISSUE TITLE
Incomprehensible behavior with an empty row

### ISSUE THREAD

**Issue by ikocs** [foprel/openpyxl-dictreader#6]
Good afternoon.  Thanks for the helpful script!  I don't understand one piece of code in it:

```python
while row == []:
            row = next(iter(self.ws_list))
```

Firstly, I cannot imagine in what case the program should be included in this part of the code.  

And secondly, I cannot understand where the variable `self.ws_list` comes from.

**Comment by foprel** [comment]
Hello @ikocs,

Thank you for reaching out. This issue has been resolved with pull request #9. A new version has been published at PyPI, which makes it easy to upgrade the package using pip.

Let us know if you have any other suggestions for improvement.

Best,

Frank
